services:
  java-service:
    build:
      context: ./services/java
      dockerfile: Dockerfile
    ports:
      - "8021:8080"
    environment:
      - JAVA_OPTS=-Xmx1800m -XX:+UseG1GC -XX:+UseStringDeduplication
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - benchmark-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3